### ISSUE TITLE
Unable to use the histogram_quantile function for unbound_response_time_seconds_bucket 

### ISSUE THREAD

**Issue by pgporada** [kumina/unbound_exporter#4]
I would like to graph percentiles using https://prometheus.io/docs/practices/histograms/ and `unbound_response_time_seconds_bucket ` seems to provide the data I need. However when trying to graph it with the following query, no data is returned.

```
histogram_quantile(0.95, sum(rate(unbound_response_time_seconds_bucket[5m])) by (le))
```

If I use this query instead, I can see all of the buckets. The data is pretty useless though because there are 50+ buckets of various response times.
```
sum(rate(unbound_response_time_seconds_bucket[5m]))
```

I know that the unbound_exporter just passes code along from `unbound-control`, but have you experienced this and if so, how did you get the graph to work?

**Comment by EdSchouten** [comment]
Hi Phil,

I just looked into it and it seems there are two problems with the way we export the histogram:

- We only provide `*_bucket`. There is no `*_count` and `*_sum`. Unfortunately, we cannot provide `*_sum`, as Unbound simply does not export this information. That said, `*_count` can be provided relatively easily.
- The histogram isn't cumulative. This is what's causing the issues in your case.

Let me look into fixing these issues.

**Comment by pgporada** [comment]
You're the man, Ed!

**Comment by EdSchouten** [comment]
I didn't have any time for this today, but a colleague of mine did (Thanks, Bart!). He just change the code to make use of an actual histogram object. Even though there is no way to compute the `*_sum`, it now approximates it by multiplying the sample count by the bucket's average value. Not ideal, but not bad either.

**Comment by jsha** [comment]
Would you be willing to [file a bug on Unbound](https://www.nlnetlabs.nl/labs/bugs/) to export the necessary information?

**Comment by EdSchouten** [comment]
Done! https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=3114
